Módulo_4/Mod4_Aula02_17_08_2021/BlueDev/Models/Alunos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlueDev.Models
{
    public class Alunos
    {
        public int Id { get; set; }
        public string Nome { get; set; }

        public DateTime Nascimento { get; set; }

        public int? linguagensId { get; set; }

        public List<Linguagens> linguagens { get; set; }
        
    }
}

Módulo_4/Mod4_Aula02_17_08_2021/BlueDev/Models/ErrorViewModel.cs
using System;

namespace BlueDev.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Módulo_4/Mod4_Aula02_17_08_2021/BlueDev/Models/Linguagens.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BlueDev.Models
{
    public class Linguagens
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Aplicacao { get; set; }

        public DateTime Lancamento { get; set; }

        public string Desenvolvedor { get; set; }
        public string Logo { get; set; }

        public List<Alunos> Alunos { get; set; }
    }
}

Módulo_4/Mod4_Aula02_17_08_2021/BlueDev/Models/Public.cs
internal class Public
{
}

Módulo_4/Mod4_Aula02_17_08_2021/BlueDev/Controllers/AlunosController.cs
using BlueDev.Models;
using BlueDev.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlueDev.Controllers
{
    //Controllers são responsáveis por trabalhar e buscar dados que serão utilizados para o usuário.
    public class AlunosController : Controller
    {
        IAlunosService service;

        public AlunosController(IAlunosService service)
        {
            this.service = service;
        }

        public IActionResult Index(/*string busca, bool ordenar = false*/)
        {
            //ViewBag.ordenar = ordenar;
            //Random r = new Random();

            return View(service.getAll(/*ordenar*/));
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Alunos alunos)
        {
            if (!ModelState.IsValid) return View(alunos);

            return service.create(alunos) ?
                RedirectToAction(nameof(Index)) :
                View(alunos);
        }


        public IActionResult Read(int? id)
        {
            Alunos alunos = service.get(id);
            return alunos != null ?
                View(alunos) :
                NotFound();
        }

        public IActionResult Update(int? id)
        {
            Alunos alunos = service.get(id);
            return alunos != null ?
                View(alunos) :
                NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Alunos alunos)
        {
            if (!ModelState.IsValid) return View(alunos);

            if (service.update(alunos))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(alunos);
            }
        }

        public IActionResult Delete(int? id)
        {
            if (service.delete(id))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }
    }
}

Módulo_4/Mod4_Aula02_17_08_2021/BlueDev/Controllers/HomeController.cs
using BlueDev.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BlueDev.Controllers
{
    public class HomeController : Controller
    {

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Info()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        
    }
}

Módulo_4/Mod4_Aula02_17_08_2021/BlueDev/Controllers/LinguagensController.cs
using BlueDev.Models;
using BlueDev.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlueDev.Controllers
{
    //Controllers são responsáveis por trabalhar e buscar dados que serão utilizados para o usuário.
    public class LinguagensController : Controller
    {
        ILinguagensService service;

        public LinguagensController(ILinguagensService service)
        {
            this.service = service;
        }

        public IActionResult Index(string busca, bool ordenar = false)
        {
            ViewBag.ordenar = ordenar;
            Random r = new Random();

            return View(service.getAll(busca, ordenar));
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Linguagens linguagens)
        {
            if (!ModelState.IsValid) return View(linguagens);

            return service.create(linguagens) ?
                RedirectToAction(nameof(Index)) :
                View(linguagens);
        }


        public IActionResult Read(int? id)
        {
            Linguagens linguagens = service.get(id);
            return linguagens != null ?
                View(linguagens) :
                NotFound();
        }

        public IActionResult Update(int? id)
        {
            Linguagens linguagens = service.get(id);
            return linguagens != null ?
                View(linguagens) :
                NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Linguagens linguagens)
        {
            if (!ModelState.IsValid) return View(linguagens);

            if (service.update(linguagens)) 
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(linguagens);
            }
        }

        public IActionResult Delete(int? id)
        {
            if (service.delete(id)) 
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }
    }
}

Módulo_4/Mod4_Aula02_17_08_2021/BlueDev/Views/Linguagens/Create.cshtml
@model Linguagens

<div class="row">
    <form class="col-md-4" asp-action="Create">
        <div class="form-group">
            <label asp-for="Nome" class="control-label"></label>
            <input asp-for="Nome" class="form-control" />
            <span class="text-danger" asp-validation-for="Nome"></span>
        </div>
        <div class="form-group">
            <label asp-for="Aplicacao" class="control-label"></label>
            <input asp-for="Aplicacao" class="form-control" />
            <span class="text-danger" asp-validation-for="Aplicacao"></span>
        </div>
        <div class="form-group">
            <label asp-for="Lancamento" class="control-label"></label>
            <input asp-for="Lancamento" class="form-control" />
            <span class="text-danger" asp-validation-for="Lancamento"></span>
        </div>
        <div class="form-group">
            <label asp-for="Desenvolvedor" class="control-label"></label>
            <input asp-for="Desenvolvedor" class="form-control" />
            <span class="text-danger" asp-validation-for="Desenvolvedor"></span>
        </div>
        <div class="form-group">
            <label asp-for="Logo" class="control-label"></label>
            <input asp-for="Logo" class="form-control" />
            <span class="text-danger" asp-validation-for="Logo"></span>
        </div>
        <div class="form-group">
            <input class="btn btn-success" type="submit" value="Criar!" />
            <a class="btn btn-info" asp-controller="Linguagens" asp-action="Index">Voltar!</a>
        </div>
    </form>
</div><br><br>

<a class="btn btn-info" asp-controller="Linguagens" asp-action="Index">Voltar!</a>

Módulo_4/Mod4_Aula02_17_08_2021/BlueDev/Views/Linguagens/Index.cshtml
@model List<Linguagens>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<h2>Lista de Linguagens</h2>
<a class="btn btn-info" asp-controller="Linguagens" asp-action="Create">Cadastrar Linguagem!</a>
<br>
<br>


<form class="row">
    <div class="col col-md-4">
        <input type="text" class="form-control" name="busca" placeholder="Buscar..." />
    </div><br>
    <div class="col col-md-2">
        <button type="submit" class="btn btn-info">Buscar!</button>
    </div>
</form>
<br>
<br>

<div class="row">
    <div class="col">
        @if (ViewBag.ordenar == true)
        {
            <a asp-action="Index" class="btn btn-outline-info">Remover ordenação!</a><br>
        }
        else
        {
            <a href="?ordenar=true" class="btn btn-info">Ordenar!</a><br>
        }
    </div>
</div>
<br>
<br>

<div>
    <table class="table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(Model => Model.First().Id)</th>
                <th>@Html.DisplayNameFor(Model => Model.First().Nome)</th>
                <th>@Html.DisplayNameFor(Model => Model.First().Logo)</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Linguagens linguagens in Model) // { 1, p1, x} {2, p2, y} ...
            {
                var classe = linguagens.Alunos.Count > 0 ? "text-info" : "";
                string alunosQtde = linguagens.Alunos.Count > 0 ? $" - {linguagens.Alunos.Count}" : "";
                <tr class="@classe">
                    <td> @Html.DisplayFor(Model => linguagens.Id) </td>
                    <td> @Html.DisplayFor(Model => linguagens.Nome) <span>@alunosQtde</span></td>
                    <td> @Html.DisplayFor(Model => linguagens.Logo) </td>
                    <td>
                        <a asp-controller="Linguagens" asp-action="Read" asp-route-id="@linguagens.Id">Visualizar</a> |
                        <a asp-controller="Linguagens" asp-action="Update" asp-route-id="@linguagens.Id">Atualizar</a> |
                        <a asp-controller="Linguagens" asp-action="Delete" asp-route-id="@linguagens.Id">Deletar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div>
        @if (SignInManager.IsSignedIn(User))
        {
            <a asp-action="Create" class="btn btn-info">Nova Linguagem!</a>
        }
    </div>
</div>
<br>


<a class="btn btn-info" asp-controller="Home" asp-action="Index">Voltar!</a>

Módulo_4/Mod4_Aula02_17_08_2021/BlueDev/Views/Linguagens/Read.cshtml
@model Linguagens

@if (Model == null)
{
    <h1>LINGUAGEM NÃO EXISTE</h1>
    <a asp-action="Index">Voltar</a>
}
else
{

<h1>Visualizando Linguagem @Model.Id</h1>


<dl class="row">
    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.Id)</dt>
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.Id)</dd>

    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.Logo)</dt>
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.Logo)</dd>

    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.Lancamento)</dt>
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.Lancamento)</dd>

    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.Desenvolvedor)</dt>
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.Desenvolvedor)</dd>

    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.Aplicacao)</dt>
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.Aplicacao)</dd>
</dl>

    @if (Model.Alunos.Count > 0)
    {
        <h3>Consultas: </h3>
        @foreach (Alunos a in Model.Alunos)
        {
            <p><strong> @Html.DisplayFor(x => a.Nome)</strong> - @Html.DisplayFor(x => a.Nascimento)</p>
        }
    }



    <a class="btn btn-info" asp-controller="Linguagens" asp-action="Index">Voltar!</a>

}

Módulo_4/Mod4_Aula02_17_08_2021/BlueDev/Views/Linguagens/Update.cshtml
@model Linguagens

<h4>
    Atualizar a linguagem
</h4>

<div class="row">
    <form class="col-md-4" asp-action="Update">
        <input type="hidden" asp-for="Id" />

        <div class="form-group">
            <label asp-for="Nome" class="control-label"></label>
            <input asp-for="Nome" class="form-control" />
            <span class="text-danger" asp-validation-for="Nome"></span>
        </div>
        <div class="form-group">
            <label asp-for="Aplicacao" class="control-label"></label>
            <input asp-for="Aplicacao" class="form-control" />
            <span class="text-danger" asp-validation-for="Aplicacao"></span>
        </div>
        <div class="form-group">
            <label asp-for="Lancamento" class="control-label"></label>
            <input asp-for="Lancamento" class="form-control" />
            <span class="text-danger" asp-validation-for="Lancamento"></span>
        </div>
        <div class="form-group">
            <label asp-for="Desenvolvedor" class="control-label"></label>
            <input asp-for="Desenvolvedor" class="form-control" />
            <span class="text-danger" asp-validation-for="Desenvolvedor"></span>
        </div>
        <div class="form-group">
            <label asp-for="Logo" class="control-label"></label>
            <input asp-for="Logo" class="form-control" />
            <span class="text-danger" asp-validation-for="Logo"></span>
        </div>
        <div class="form-group">
            <input class="btn btn-success" type="submit" value="Criar!" />
            <a class="btn btn-info" asp-controller="Linguagens" asp-action="Index">Voltar!</a>
        </div>

    </form>
</div>

<a class="btn btn-info" asp-controller="Linguagens" asp-action="Index">Voltar!</a>